syntax = "proto3";

package console_client;

// Between Console - Client

enum ConsoleClientMessageType {
  kConsoleClientHello = 0;
  kConsoleClientHeartBeat = 1;
}

message ConsoleClientHello {
  string device_id = 1;
}

message ConsoleClientHeartBeat {
  int64 hb_index = 1;
  // !!thunder sdk!! heartbeat duration < 10'000 or not
  // < 10'000 -> alive
  // > 10'000 -> died
  bool connection_alive = 2;
}

message ConsoleClientMessage {
  ConsoleClientMessageType msg_type = 1;
  string device_id = 10;
  ConsoleClientHello hello = 20;
  ConsoleClientHeartBeat heartbeat = 30;
}