[package]
name = "px_node_protocol"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1.15.1", features = ["serde"] }
zeroize = "1.8"

[dev-dependencies]
serde_json = "1"
