include(${CMAKE_CURRENT_SOURCE_DIR}/px_base/version.cmake)
include_directories(${CMAKE_BINARY_DIR}/src/px_base)
add_subdirectory(px_deps)
add_subdirectory(px_base)
add_subdirectory(px_client)
add_subdirectory(px_panel)
add_subdirectory(px_render)
#add_subdirectory(GammaRayServer)
#add_subdirectory(render_plugins)
