//
// Created by RGAA on 8/12/2024.
//

#include "udp_connection.h"
#include "px_common/log.h"
#include "px_common/data.h"
#include <asio2/asio2.hpp>
#include <asio2/udp/udp_client.hpp>

namespace px
{

    UdpConnection::UdpConnection(const std::shared_ptr<ThunderSdkParams>& params,
                                 const std::shared_ptr<MessageNotifier>& notifier,
                                 const std::string& host,
                                 int port) : Connection(params, notifier) {
        this->host_ = host;
        this->port_ = port;
    }

    UdpConnection::~UdpConnection() {
        Stop();
    }

    void UdpConnection::Start() {
        const auto weak_self = weak_from_this();
        udp_client_ = std::make_shared<asio2::udp_client>();
        // Provide a kcp conv, If the conv is not provided, it will be generated by the server.
        udp_client_->set_kcp_conv(12);

        udp_client_->bind_connect([weak_self]() {
            const auto self = weak_self.lock();
            if (!self || !self->udp_client_) return;
            if (asio2::get_last_error())
                LOGI("udp connect failure : {} {}", asio2::last_error_val(), asio2::last_error_msg().c_str());
            else {
                LOGI("udp connect success : {} {}", self->udp_client_->local_address().c_str(), self->udp_client_->local_port());
                self->udp_client_->post_queued_event([weak_self]() {
                    if (const auto locked = weak_self.lock(); locked && locked->conn_cbk_) {
                        locked->conn_cbk_();
                    }
                });
            }

        }).bind_disconnect([weak_self]() {
            LOGI("disconnect : {} {}", asio2::last_error_val(), asio2::last_error_msg().c_str());
            if (const auto self = weak_self.lock(); self && self->dis_conn_cbk_) {
                self->dis_conn_cbk_();
            }

        }).bind_recv([weak_self](std::string_view data) {
            if (const auto self = weak_self.lock(); self && self->msg_cbk_) {
                auto cpy_data = Data::From(data);
                self->msg_cbk_(cpy_data);
            }

        }).bind_handshake([]() {
            if (asio2::get_last_error())
                LOGI("handshake failure : {} {}",
                       asio2::last_error_val(), asio2::last_error_msg().c_str());
            else
                LOGI("handshake success : {} {}",
                       asio2::last_error_val(), asio2::last_error_msg().c_str());
        }).bind_init([]() {
            // Specify the local port to which the socket is bind.
            //asio::ip::udp::endpoint ep(asio::ip::udp::v4(), 1234);
            //client.socket().bind(ep);
        });

        // to use kcp, the last param must be : asio2::use_kcp
        udp_client_->async_start(host_, port_, asio2::use_kcp);
    }

    void UdpConnection::Stop() {
        if (udp_client_ && udp_client_->is_started()) {
            udp_client_->stop_all_timers();
            udp_client_->stop();
        }
    }

    void UdpConnection::PostBinaryMessage(std::shared_ptr<Data> msg) {
        if (udp_client_ && udp_client_->is_started()) {
            queuing_message_count_++;
            const auto weak_self = weak_from_this();
            udp_client_->async_send(msg->Bytes().data(), msg->Size(), [weak_self]() {
                if (const auto self = weak_self.lock()) self->queuing_message_count_--;
            });
        }
    }

}
