/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactUs: typeof import('./src/components/ContactUs.vue')['default']
    DotGlobe: typeof import('./src/components/DotGlobe.vue')['default']
    FeatureSection: typeof import('./src/components/FeatureSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ContactUs: typeof import('./src/components/ContactUs.vue')['default']
  const DotGlobe: typeof import('./src/components/DotGlobe.vue')['default']
  const FeatureSection: typeof import('./src/components/FeatureSection.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}