plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace = 'yun.pixels.client.feature.devices'
    compileSdk = 37

    defaultConfig {
        minSdk = 31
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

}

dependencies {
    implementation project(':core-domain')

    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0'
    implementation platform('androidx.compose:compose-bom:2026.08.00')
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'

    debugImplementation 'androidx.compose.ui:ui-tooling'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2'
}
