#include "px_ui/localization.h"

#include <array>
#include <cstddef>
#include <utility>

namespace px::ui {
namespace {

constexpr std::size_t kTextCount{std::to_underlying(TextId::Count)};
using Catalog = std::array<std::string_view, kTextCount>;

constexpr Catalog kEnglish{
    "Render node console",
    "Remote control",
    "Cloud Apps",
    "Runtime Environment",
    "Security",
    "Settings",
    "Hardware",
    "Exit programs",
    "Settings / Network",
    "Connection addresses and node service ports",
    "Authorization",
    "Resolved control endpoints",
    "Supervisor",
    "Node management and status",
    "Relay",
    "Reliable routed connection",
    "Node public address",
    "Optional. Leave empty when automatic address detection is suitable.",
    "Public IP or hostname",
    "Node listening ports",
    "Service management port",
    "Local service management",
    "Desktop connection port",
    "Desktop render connection",
    "Application port pool",
    "Dynamically allocated applications",
    "RTC media pool",
    "Browser sessions",
    "Panel listening port",
    "Local panel API",
    "Save",
    "Verify",
    "Authorization information is invalid.",
    "The public address is invalid.",
    "Verifying...",
    "Verification succeeded.",
    "Saving...",
    "Saved.",
    "Operation failed.",
    "Settings are saved. Restart the render service now?",
    "Restart now",
    "Later",
    "UI preview: existing Panel services are not connected yet.",
    "Preview saved locally. Business persistence is intentionally not connected.",
    "English",
    "简体中文",
    "Language",
    "Theme",
    "Dark",
    "Light",
    "Enhanced visual effects",
    "This device",
    "Device ID",
    "Temporary password",
    "Device name",
    "Connection information",
    "Desktop link",
    "Web client address",
    "Copy",
    "Open",
    "Show",
    "Hide",
    "Device ID, link://, or IP[:port]",
    "Connect",
    "Remote devices",
    "Online",
    "Offline",
    "Start control",
    "View only",
    "Stop control",
    "Manager service",
    "No remote devices are available.",
    "Refresh",
    "Application",
    "State",
    "Running",
    "Stopped",
    "Start application",
    "Enter application",
    "Stop application",
    "Force TCP",
    "Force relay",
    "No cloud applications are available.",
    "Gamepad driver",
    "Render service",
    "Node service",
    "Ready",
    "Unavailable",
    "Install",
    "Restart",
    "Shutdown",
    "Network addresses",
    "Wired",
    "Wireless",
    "Audio format",
    "General",
    "Network",
    "Controller",
    "About",
    "Encoder settings",
    "Bitrate (Mbps)",
    "Frame rate",
    "Video codec",
    "Resize resolution",
    "Width",
    "Height",
    "Capture audio",
    "Bitrate must be greater than zero.",
    "Frame rate must be between 15 and 144.",
    "Resolution must use even dimensions and be at least 600 x 200.",
    "The selected codec does not support this resolution.",
    "The resolution aspect ratio cannot exceed 4:1.",
    "Client window settings",
    "Maximize client window",
    "Display client logo",
    "Colorful title bar",
    "Maximum screens",
    "Preferred decoder",
    "Automatic",
    "Hardware",
    "Software",
    "Screen recording path",
    "Security settings",
    "Lock the screen after the last client disconnects",
    "Long-term password",
    "Confirm password",
    "Set password",
    "Passwords must be non-empty and identical.",
    "Maintenance tools",
    "Clear application data",
    "Clear all local Pixels data? This action cannot be undone.",
    "Clear",
    "Cancel",
    "Version",
    "Pixels keeps render nodes online and provides secure remote desktop and cloud application access.",
    "Check for updates",
    "Website",
    "Visit history",
    "File transfer history",
    "Clear all",
    "No security records.",
    "Connection type",
    "Result",
    "Start time",
    "End time",
    "Visitor device",
    "Target device",
    "Duration",
    "Direction",
    "File name",
    "Actions",
    "Copy JSON",
    "Delete",
    "Enter the long-term password to continue.",
    "Updating the password...",
    "Password updated.",
    "The local password was updated, but synchronization to the management service failed.",
    "Log archive destination",
    "Collect logs",
    "Collecting...",
    "Log archive created.",
    "Log collection failed.",
    "Account",
    "Guest",
    "Sign in",
    "Sign out",
    "Register",
    "Username",
    "Password",
    "Confirm",
    "Working...",
    "The account operation failed. Check the server connection and credentials.",
    "Enter a username and matching non-empty passwords.",
    "More",
    "File transfer",
    "Lock device",
    "Restart device",
    "Shut down device",
    "Confirm this device operation?",
    "Edit device",
    "Host",
    "Port",
    "Device settings",
    "Enable clipboard",
    "Split windows by display",
    "Force software decoding",
    "Wait for debugger",
    "Force GDI capture",
    "Disable Vulkan rendering",
    "Enter a name and a valid port when a host is specified.",
    "Connected clients",
    "This page is pending UI migration; the existing product workflow remains unchanged.",
    "Incoming voice call",
    "A remote visitor is requesting a voice call:",
    "Accept only when you recognize and trust this visitor.",
    "Time remaining (seconds):",
    "Accept",
    "Reject",
    "Device list",
    "Search by name or device ID",
    "All devices",
    "Device details",
    "Select a device to view its details.",
    "Remove this device from recent devices and the device list?",
    "Connect to a remote device",
    "Recent devices",
    "Connection credentials",
    "Allow remote access",
    "Share and web access",
    "Total",
    "QR code",
    "Personal center",
    "Change avatar",
    "Select image",
    "Update name",
    "Current password",
    "New password",
    "Confirm new password",
    "Update password",
    "Enter a non-empty name.",
    "Enter the current password and matching non-empty new passwords.",
    "Connection progress",
    "Validate connection target",
    "Resolve device and address",
    "Contact remote service",
    "Check permission and connection availability",
    "Verify device password",
    "Start connection process",
    "The connection target is incomplete or malformed.",
    "Device ID lookup requires a signed-in Console account.",
    "The management service could not resolve this device.",
    "No usable remote address or service port was found.",
    "The remote desktop service could not be reached.",
    "The remote device does not support connection preflight. Update Pixels on the remote device.",
    "The remote device has disabled incoming remote access.",
    "The remote device has disabled file transfer.",
    "The remote desktop is occupied. Please try again shortly.",
    "The remote desktop is occupied. Please try again shortly.",
    "A current remote-device password is required.",
    "The remote device rejected the supplied password.",
    "The remote service responded, but password verification was unavailable.",
    "All checks passed, but the connection process could not be started.",
    "The Panel background worker is unavailable.",
    "Waiting",
    "Enable remote access?",
    "New desktop-control and file-transfer connections will be allowed.",
    "Disable remote access?",
    "New desktop-control and file-transfer connections will be rejected.",
    "Processor",
    "Memory",
    "Storage",
    "Graphics card",
    "Graphics driver",
    "Software",
    "System version",
    "Audio service",
    "Visual C++ runtime",
    "Legacy DirectX components",
    "Automatically log in to Windows at startup",
    "Never turn off the display",
    "System never sleeps",
    "High performance mode",
    "System settings",
    "Pending system restart",
    "Checking",
    "Attention",
    "Recommended",
    "Not configured",
    "Open settings",
    "Download",
    "Learn more",
    "AC",
    "Battery",
    "Never",
    "min",
    "Unknown",
    "Machine information is not available yet.",
};

constexpr Catalog kSimplifiedChinese{
    "渲染节点控制台",
    "远程控制",
    "云端应用",
    "运行环境",
    "安全",
    "设置",
    "硬件",
    "退出程序",
    "设置 / 网络",
    "连接地址与节点服务端口",
    "授权信息",
    "解析后的控制端点",
    "管理服务",
    "节点管理与状态",
    "转发服务",
    "可靠转发连接",
    "节点公网地址",
    "可选。自动地址探测可用时请留空。",
    "公网 IP 或域名",
    "节点监听端口",
    "服务管理端口",
    "本机服务管理",
    "桌面连接端口",
    "桌面渲染连接",
    "应用端口池",
    "动态分配的应用端口",
    "RTC 媒体端口池",
    "浏览器会话",
    "Panel 监听端口",
    "本机 Panel 接口",
    "保存",
    "验证",
    "授权信息无效。",
    "节点公网地址无效。",
    "正在验证……",
    "验证成功。",
    "正在保存……",
    "已保存。",
    "操作失败。",
    "设置已保存，是否立即重启渲染服务？",
    "立即重启",
    "稍后",
    "UI 预览：尚未连接现有 Panel 服务。",
    "预览设置已保存在本地，尚未接入业务持久化。",
    "English",
    "简体中文",
    "语言",
    "主题",
    "深色",
    "浅色",
    "增强视觉效果",
    "本机设备",
    "设备 ID",
    "临时密码",
    "设备名称",
    "连接信息",
    "桌面链接",
    "网页客户端地址",
    "复制",
    "打开",
    "显示",
    "隐藏",
    "设备 ID、link:// 或 IP[:端口]",
    "连接",
    "远程设备",
    "在线",
    "离线",
    "开始控制",
    "仅观看",
    "停止控制",
    "管理服务",
    "暂无远程设备。",
    "刷新",
    "应用",
    "状态",
    "运行中",
    "已停止",
    "启动应用",
    "进入应用",
    "停止应用",
    "强制 TCP",
    "强制转发",
    "暂无云应用。",
    "手柄驱动器",
    "渲染服务",
    "节点服务",
    "正常",
    "不可用",
    "安装",
    "重启",
    "关机",
    "网络地址",
    "有线",
    "无线",
    "音频格式",
    "常规",
    "网络",
    "控制器",
    "关于",
    "编码设置",
    "码率（Mbps）",
    "帧率",
    "视频编码",
    "调整分辨率",
    "宽度",
    "高度",
    "采集音频",
    "码率必须大于零。",
    "帧率必须在 15 到 144 之间。",
    "分辨率必须为偶数，且不小于 600 x 200。",
    "所选编码不支持该分辨率。",
    "分辨率宽高比不能超过 4:1。",
    "客户端窗口设置",
    "最大化客户端窗口",
    "显示客户端标志",
    "彩色标题栏",
    "最大屏幕数量",
    "首选解码器",
    "自动",
    "硬件",
    "软件",
    "录屏保存路径",
    "安全设置",
    "最后一个客户端断开后锁定屏幕",
    "长期密码",
    "确认密码",
    "设置密码",
    "密码不能为空且两次输入必须一致。",
    "维护工具",
    "清除应用数据",
    "确定清除 Pixels 的全部本地数据吗？此操作无法撤销。",
    "清除",
    "取消",
    "版本",
    "Pixels 用于保持渲染节点在线，并提供安全的远程桌面和云应用访问。",
    "检查更新",
    "官方网站",
    "访问记录",
    "文件传输记录",
    "全部清除",
    "暂无安全记录。",
    "连接类型",
    "结果",
    "开始时间",
    "结束时间",
    "访问设备",
    "目标设备",
    "持续时间",
    "方向",
    "文件名",
    "操作",
    "复制 JSON",
    "删除",
    "请输入长期密码以继续。",
    "正在更新密码……",
    "密码已更新。",
    "本地密码已更新，但同步到管理服务失败。",
    "日志压缩包保存目录",
    "收集日志",
    "正在收集……",
    "日志压缩包已生成。",
    "日志收集失败。",
    "账户",
    "访客",
    "登录",
    "退出登录",
    "注册",
    "用户名",
    "密码",
    "确认",
    "正在处理……",
    "账户操作失败，请检查服务连接和账户信息。",
    "请输入用户名，并确保非空密码填写一致。",
    "更多",
    "文件传输",
    "锁定设备",
    "重启设备",
    "关闭设备",
    "确定执行此设备操作吗？",
    "编辑设备",
    "主机",
    "端口",
    "设备设置",
    "启用剪贴板",
    "按显示器拆分窗口",
    "强制软件解码",
    "等待调试器",
    "强制 GDI 采集",
    "禁用 Vulkan 渲染",
    "请输入设备名称；填写主机时端口必须有效。",
    "已连接客户端",
    "该页面正在迁移 UI，现有产品业务流程保持不变。",
    "语音呼叫请求",
    "远端访问者请求与你进行语音通话：",
    "仅在确认并信任该访问者时接受请求。",
    "剩余时间（秒）：",
    "接受",
    "拒绝",
    "设备列表",
    "搜索设备名称或设备 ID",
    "所有设备",
    "设备详情",
    "请选择一个设备查看详情。",
    "确定从最近设备和设备列表中移除此设备吗？",
    "连接到远程设备",
    "最近的设备",
    "连接凭据",
    "允许被控制",
    "分享与网页访问",
    "共",
    "二维码",
    "个人中心",
    "更换头像",
    "选择图片",
    "修改名称",
    "当前密码",
    "新密码",
    "确认新密码",
    "修改密码",
    "请输入非空名称。",
    "请输入当前密码，并确保两次新密码一致且非空。",
    "连接进度",
    "检查连接目标",
    "解析设备与地址",
    "连接远程服务",
    "检查权限与连接状态",
    "验证设备密码",
    "启动连接进程",
    "连接目标不完整或格式错误。",
    "使用设备 ID 查询需要先登录管理服务账号。",
    "管理服务无法解析该设备。",
    "没有找到可用的远程地址或服务端口。",
    "无法连接远程桌面服务。",
    "远程设备不支持连接前置探测，请更新远程设备上的 Pixels。",
    "对方已禁止远程控制。",
    "对方已禁止文件传输。",
    "远程桌面已被占用，请稍后重试。",
    "远程桌面已被占用，请稍后重试。",
    "需要输入远程设备当前的密码。",
    "远程设备拒绝了该密码。",
    "远程服务已响应，但密码验证接口不可用。",
    "全部检查已通过，但无法启动连接进程。",
    "Panel 后台工作线程不可用。",
    "等待中",
    "开启允许被控制？",
    "开启后，将允许新的桌面远控和文件传输连接。",
    "关闭允许被控制？",
    "关闭后，将拒绝新的桌面远控和文件传输连接。",
    "处理器",
    "内存",
    "硬盘",
    "显卡",
    "显卡驱动",
    "软件",
    "系统版本",
    "音频服务",
    "Visual C++ 运行环境",
    "旧版 DirectX 组件",
    "开机后自动登录 Windows",
    "从不关闭显示器",
    "系统从不休眠",
    "高性能模式",
    "系统设置",
    "系统待重启",
    "检测中",
    "需注意",
    "建议设置",
    "未配置",
    "打开设置",
    "下载",
    "了解更多",
    "接通电源",
    "电池",
    "从不",
    "分钟",
    "未知",
    "暂未获取到机器信息。",
};

static_assert(kEnglish.size() == kTextCount);
static_assert(kSimplifiedChinese.size() == kTextCount);

} // namespace

Localizer::Localizer(const Language language) noexcept : language_{language} {}

void Localizer::SetLanguage(const Language language) noexcept {
    language_ = language;
}

Language Localizer::CurrentLanguage() const noexcept {
    return language_;
}

std::string_view Localizer::Text(const TextId id) const noexcept {
    const std::size_t index{std::to_underlying(id)};
    if (index >= kTextCount) {
        return {};
    }
    return language_ == Language::SimplifiedChinese ? kSimplifiedChinese[index] : kEnglish[index];
}

bool CatalogsAreComplete() noexcept {
    const auto complete = [](const Catalog& catalog) {
        for (const std::string_view text : catalog) {
            if (text.empty()) {
                return false;
            }
        }
        return true;
    };
    return complete(kEnglish) && complete(kSimplifiedChinese);
}

} // namespace px::ui
