// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsServiceHello {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub appkey: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsServiceHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub render_alive: bool,
    /// json format authorization info reported by the panel (may be empty)
    #[prost(string, tag = "4")]
    pub auth_info_json: ::prost::alloc::string::String,
    /// json array of local app instance summaries (may be empty)
    /// \[{instance_id, app_id, listen_port, pid, state}, ...\]
    #[prost(string, tag = "5")]
    pub instances_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsServiceStartAppInstance {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub app_id: ::prost::alloc::string::String,
    /// Absolute install root on this machine (Placement.install_root)
    #[prost(string, tag = "4")]
    pub install_root: ::prost::alloc::string::String,
    /// Relative exe path under install_root (Application.game_exe_rel)
    #[prost(string, tag = "5")]
    pub game_exe_rel: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub game_arguments: ::prost::alloc::string::String,
    /// 0 = Service allocates an available port
    #[prost(int32, tag = "7")]
    pub listen_port: i32,
    #[prost(int32, tag = "8")]
    pub encoder_fps: i32,
    #[prost(int32, tag = "9")]
    pub encoder_bitrate: i32,
    #[prost(string, tag = "10")]
    pub encoder_format: ::prost::alloc::string::String,
    #[prost(bool, tag = "11")]
    pub webrtc_enabled: bool,
    #[prost(bool, tag = "12")]
    pub websocket_enabled: bool,
    /// Deterministic CMS live stream name, normally \<device_id>**app**\<app_id>.
    /// Empty keeps backward compatibility and disables the passive RTMP pusher.
    #[prost(string, tag = "13")]
    pub live_stream_id: ::prost::alloc::string::String,
    /// RTMP publishing template, for example
    /// rtmp://127.0.0.1:1935/live/{live_stream_id}. Empty uses render settings.
    #[prost(string, tag = "14")]
    pub push_rtmp_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsServiceStopAppInstance {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsServiceStartAppInstanceResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub ok: bool,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub listen_port: i32,
    #[prost(uint32, tag = "6")]
    pub pid: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsServiceStopAppInstanceResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub ok: bool,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsServiceMessage {
    #[prost(enumeration = "CmsServiceMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "10")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub hello: ::core::option::Option<CmsServiceHello>,
    #[prost(message, optional, tag = "30")]
    pub heartbeat: ::core::option::Option<CmsServiceHeartBeat>,
    #[prost(message, optional, tag = "40")]
    pub start_app_instance: ::core::option::Option<CmsServiceStartAppInstance>,
    #[prost(message, optional, tag = "50")]
    pub stop_app_instance: ::core::option::Option<CmsServiceStopAppInstance>,
    #[prost(message, optional, tag = "60")]
    pub start_app_instance_result: ::core::option::Option<
        CmsServiceStartAppInstanceResult,
    >,
    #[prost(message, optional, tag = "70")]
    pub stop_app_instance_result: ::core::option::Option<
        CmsServiceStopAppInstanceResult,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CmsServiceMessageType {
    KCmsServiceHello = 0,
    KCmsServiceHeartBeat = 1,
    /// CMS -> Service
    KCmsServiceStartAppInstance = 2,
    KCmsServiceStopAppInstance = 3,
    /// Service -> CMS
    KCmsServiceStartAppInstanceResult = 4,
    KCmsServiceStopAppInstanceResult = 5,
}
impl CmsServiceMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KCmsServiceHello => "kCmsServiceHello",
            Self::KCmsServiceHeartBeat => "kCmsServiceHeartBeat",
            Self::KCmsServiceStartAppInstance => "kCmsServiceStartAppInstance",
            Self::KCmsServiceStopAppInstance => "kCmsServiceStopAppInstance",
            Self::KCmsServiceStartAppInstanceResult => {
                "kCmsServiceStartAppInstanceResult"
            }
            Self::KCmsServiceStopAppInstanceResult => "kCmsServiceStopAppInstanceResult",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kCmsServiceHello" => Some(Self::KCmsServiceHello),
            "kCmsServiceHeartBeat" => Some(Self::KCmsServiceHeartBeat),
            "kCmsServiceStartAppInstance" => Some(Self::KCmsServiceStartAppInstance),
            "kCmsServiceStopAppInstance" => Some(Self::KCmsServiceStopAppInstance),
            "kCmsServiceStartAppInstanceResult" => {
                Some(Self::KCmsServiceStartAppInstanceResult)
            }
            "kCmsServiceStopAppInstanceResult" => {
                Some(Self::KCmsServiceStopAppInstanceResult)
            }
            _ => None,
        }
    }
}
