// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsRelayHello {
    #[prost(string, tag = "1")]
    pub srv_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub srv_w3c_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub srv_local_ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub srv_grpc_port: u32,
    #[prost(uint32, tag = "6")]
    pub srv_working_port: u32,
    #[prost(string, tag = "7")]
    pub appkey: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsRelayHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsRelayMessage {
    #[prost(enumeration = "CmsRelayMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "3")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub hello: ::core::option::Option<CmsRelayHello>,
    #[prost(message, optional, tag = "10")]
    pub heartbeat: ::core::option::Option<CmsRelayHeartBeat>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CmsRelayMessageType {
    KHello = 0,
    KHeartBeat = 1,
}
impl CmsRelayMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KHello => "kHello",
            Self::KHeartBeat => "kHeartBeat",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kHello" => Some(Self::KHello),
            "kHeartBeat" => Some(Self::KHeartBeat),
            _ => None,
        }
    }
}
