// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsPanelHello {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsPanelHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub desktop_link: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub desktop_link_raw: ::prost::alloc::string::String,
    /// json format hardware system info
    #[prost(string, tag = "5")]
    pub sys_info_raw: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub device_ip_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub device_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsSysInfo {
    #[prost(string, tag = "1")]
    pub info: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CmsPanelMessage {
    #[prost(enumeration = "CmsPanelMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "10")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub hello: ::core::option::Option<CmsPanelHello>,
    #[prost(message, optional, tag = "30")]
    pub heartbeat: ::core::option::Option<CmsPanelHeartBeat>,
    #[prost(message, optional, tag = "40")]
    pub sys_info: ::core::option::Option<CmsSysInfo>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CmsPanelMessageType {
    KCmsPanelHello = 0,
    KCmsPanelHeartBeat = 1,
}
impl CmsPanelMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KCmsPanelHello => "kCmsPanelHello",
            Self::KCmsPanelHeartBeat => "kCmsPanelHeartBeat",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kCmsPanelHello" => Some(Self::KCmsPanelHello),
            "kCmsPanelHeartBeat" => Some(Self::KCmsPanelHeartBeat),
            _ => None,
        }
    }
}
