// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsolePanelHello {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_name: ::prost::alloc::string::String,
    /// local NIC IPv4 list (loopback / link-local excluded), reported at handshake
    /// for the console render-records view (docs/console_render_records_view_design.md 5.2)
    #[prost(string, repeated, tag = "4")]
    pub panel_lan_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// panel http server port (records api, default 20369)
    #[prost(int32, tag = "5")]
    pub panel_http_port: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsolePanelHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub desktop_link: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub desktop_link_raw: ::prost::alloc::string::String,
    /// json format hardware system info
    #[prost(string, tag = "5")]
    pub sys_info_raw: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub device_ip_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub device_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleSysInfo {
    #[prost(string, tag = "1")]
    pub info: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordFileInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub size: i64,
    /// unix seconds
    #[prost(int64, tag = "3")]
    pub mtime: i64,
    #[prost(string, tag = "4")]
    pub monitor: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub codec: ::prost::alloc::string::String,
}
/// console -> panel: request the record file list of the device
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordListReq {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub req_id: ::prost::alloc::string::String,
}
/// panel -> console: response of RecordListReq (matched by req_id)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordListResp {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub files: ::prost::alloc::vec::Vec<RecordFileInfo>,
    /// non-empty when the listing failed
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
/// console -> panel: fetch one record file; panel uploads it to upload_url
/// (POST /api/v1/record/upload, multipart, token checked by console)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordFetchReq {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub upload_url: ::prost::alloc::string::String,
}
/// panel -> console: upload finished / failed
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordFetchDone {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub ok: bool,
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RtcIceConfigChanged {
    #[prost(uint64, tag = "1")]
    pub revision: u64,
    #[prost(int64, tag = "2")]
    pub changed_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsolePanelMessage {
    #[prost(enumeration = "ConsolePanelMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "10")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub hello: ::core::option::Option<ConsolePanelHello>,
    #[prost(message, optional, tag = "30")]
    pub heartbeat: ::core::option::Option<ConsolePanelHeartBeat>,
    #[prost(message, optional, tag = "40")]
    pub sys_info: ::core::option::Option<ConsoleSysInfo>,
    #[prost(message, optional, tag = "50")]
    pub record_list_req: ::core::option::Option<RecordListReq>,
    #[prost(message, optional, tag = "51")]
    pub record_list_resp: ::core::option::Option<RecordListResp>,
    #[prost(message, optional, tag = "52")]
    pub record_fetch_req: ::core::option::Option<RecordFetchReq>,
    #[prost(message, optional, tag = "53")]
    pub record_fetch_done: ::core::option::Option<RecordFetchDone>,
    #[prost(message, optional, tag = "60")]
    pub rtc_ice_config_changed: ::core::option::Option<RtcIceConfigChanged>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConsolePanelMessageType {
    KConsolePanelHello = 0,
    KConsolePanelHeartBeat = 1,
    KRecordListReq = 2,
    KRecordListResp = 3,
    KRecordFetchReq = 4,
    KRecordFetchDone = 5,
    /// Console -> Panel. The payload is an invalidation only; Panel pulls the
    /// authenticated configuration from /api/v1/rtc/ice-config.
    KRtcIceConfigChanged = 6,
}
impl ConsolePanelMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KConsolePanelHello => "kConsolePanelHello",
            Self::KConsolePanelHeartBeat => "kConsolePanelHeartBeat",
            Self::KRecordListReq => "kRecordListReq",
            Self::KRecordListResp => "kRecordListResp",
            Self::KRecordFetchReq => "kRecordFetchReq",
            Self::KRecordFetchDone => "kRecordFetchDone",
            Self::KRtcIceConfigChanged => "kRtcIceConfigChanged",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kConsolePanelHello" => Some(Self::KConsolePanelHello),
            "kConsolePanelHeartBeat" => Some(Self::KConsolePanelHeartBeat),
            "kRecordListReq" => Some(Self::KRecordListReq),
            "kRecordListResp" => Some(Self::KRecordListResp),
            "kRecordFetchReq" => Some(Self::KRecordFetchReq),
            "kRecordFetchDone" => Some(Self::KRecordFetchDone),
            "kRtcIceConfigChanged" => Some(Self::KRtcIceConfigChanged),
            _ => None,
        }
    }
}
