// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceHello {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub appkey: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub render_alive: bool,
    /// json format authorization info reported by the panel (may be empty)
    #[prost(string, tag = "4")]
    pub auth_info_json: ::prost::alloc::string::String,
    /// json array of local app instance summaries (may be empty)
    /// \[{instance_id, app_id, listen_port, pid, state}, ...\]
    #[prost(string, tag = "5")]
    pub instances_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceStartAppInstance {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub app_id: ::prost::alloc::string::String,
    /// Absolute install root on this machine (Placement.install_root)
    #[prost(string, tag = "4")]
    pub install_root: ::prost::alloc::string::String,
    /// Relative exe path under install_root (Application.game_exe_rel)
    #[prost(string, tag = "5")]
    pub game_exe_rel: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub game_arguments: ::prost::alloc::string::String,
    /// 0 = Service allocates an available port
    #[prost(int32, tag = "7")]
    pub listen_port: i32,
    #[prost(int32, tag = "8")]
    pub encoder_fps: i32,
    #[prost(int32, tag = "9")]
    pub encoder_bitrate: i32,
    #[prost(string, tag = "10")]
    pub encoder_format: ::prost::alloc::string::String,
    #[prost(bool, tag = "11")]
    pub webrtc_enabled: bool,
    #[prost(bool, tag = "12")]
    pub websocket_enabled: bool,
    /// Deterministic Console live stream name, normally \<device_id>**app**\<app_id>.
    /// Empty keeps backward compatibility and disables the passive RTMP pusher.
    #[prost(string, tag = "13")]
    pub live_stream_id: ::prost::alloc::string::String,
    /// RTMP publishing template, for example
    /// rtmp://127.0.0.1:1935/live/{live_stream_id}. Empty uses render settings.
    #[prost(string, tag = "14")]
    pub push_rtmp_url: ::prost::alloc::string::String,
    /// Application launch mode. Empty means legacy game-hook.
    #[prost(string, tag = "15")]
    pub app_mode: ::prost::alloc::string::String,
    /// UTF-8 Base64URL (no padding) entry URL. Required for app_mode=webview.
    #[prost(string, tag = "16")]
    pub webview_url_b64: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceStopAppInstance {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceStartAppInstanceResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub ok: bool,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub listen_port: i32,
    #[prost(uint32, tag = "6")]
    pub pid: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceStopAppInstanceResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub ok: bool,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceCreateWallSession {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub render_port: i32,
    #[prost(string, tag = "5")]
    pub safety_pwd_md5: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub offer_sdp: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceCreateWallSessionResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub ok: bool,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub answer_sdp: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceRedeemConnectionTicket {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Informational only. Console uses the device identity bound to this WebSocket.
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ticket: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub client_nonce: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub instance_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleConnectionGrant {
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub app_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub subject_type: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub subject_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "8")]
    pub expires_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceRedeemConnectionTicketResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(string, tag = "3")]
    pub code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub grant: ::core::option::Option<ConsoleConnectionGrant>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsoleServiceMessage {
    #[prost(enumeration = "ConsoleServiceMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "10")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub hello: ::core::option::Option<ConsoleServiceHello>,
    #[prost(message, optional, tag = "30")]
    pub heartbeat: ::core::option::Option<ConsoleServiceHeartBeat>,
    #[prost(message, optional, tag = "40")]
    pub start_app_instance: ::core::option::Option<ConsoleServiceStartAppInstance>,
    #[prost(message, optional, tag = "50")]
    pub stop_app_instance: ::core::option::Option<ConsoleServiceStopAppInstance>,
    #[prost(message, optional, tag = "60")]
    pub start_app_instance_result: ::core::option::Option<
        ConsoleServiceStartAppInstanceResult,
    >,
    #[prost(message, optional, tag = "70")]
    pub stop_app_instance_result: ::core::option::Option<
        ConsoleServiceStopAppInstanceResult,
    >,
    #[prost(message, optional, tag = "80")]
    pub create_wall_session: ::core::option::Option<ConsoleServiceCreateWallSession>,
    #[prost(message, optional, tag = "90")]
    pub create_wall_session_result: ::core::option::Option<
        ConsoleServiceCreateWallSessionResult,
    >,
    #[prost(message, optional, tag = "100")]
    pub redeem_connection_ticket: ::core::option::Option<
        ConsoleServiceRedeemConnectionTicket,
    >,
    #[prost(message, optional, tag = "110")]
    pub redeem_connection_ticket_result: ::core::option::Option<
        ConsoleServiceRedeemConnectionTicketResult,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConsoleServiceMessageType {
    KConsoleServiceHello = 0,
    KConsoleServiceHeartBeat = 1,
    /// Console -> Service
    KConsoleServiceStartAppInstance = 2,
    KConsoleServiceStopAppInstance = 3,
    /// Service -> Console
    KConsoleServiceStartAppInstanceResult = 4,
    KConsoleServiceStopAppInstanceResult = 5,
    /// Console -> Service -> local desktop render. This trusted hop is the only
    /// authority allowed to create a hidden, read-only wall observer.
    KConsoleServiceCreateWallSession = 6,
    /// Service -> Console
    KConsoleServiceCreateWallSessionResult = 7,
    /// Service -> Console, then Console -> Service.
    KConsoleServiceRedeemConnectionTicket = 8,
    KConsoleServiceRedeemConnectionTicketResult = 9,
}
impl ConsoleServiceMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KConsoleServiceHello => "kConsoleServiceHello",
            Self::KConsoleServiceHeartBeat => "kConsoleServiceHeartBeat",
            Self::KConsoleServiceStartAppInstance => "kConsoleServiceStartAppInstance",
            Self::KConsoleServiceStopAppInstance => "kConsoleServiceStopAppInstance",
            Self::KConsoleServiceStartAppInstanceResult => {
                "kConsoleServiceStartAppInstanceResult"
            }
            Self::KConsoleServiceStopAppInstanceResult => {
                "kConsoleServiceStopAppInstanceResult"
            }
            Self::KConsoleServiceCreateWallSession => "kConsoleServiceCreateWallSession",
            Self::KConsoleServiceCreateWallSessionResult => {
                "kConsoleServiceCreateWallSessionResult"
            }
            Self::KConsoleServiceRedeemConnectionTicket => {
                "kConsoleServiceRedeemConnectionTicket"
            }
            Self::KConsoleServiceRedeemConnectionTicketResult => {
                "kConsoleServiceRedeemConnectionTicketResult"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kConsoleServiceHello" => Some(Self::KConsoleServiceHello),
            "kConsoleServiceHeartBeat" => Some(Self::KConsoleServiceHeartBeat),
            "kConsoleServiceStartAppInstance" => {
                Some(Self::KConsoleServiceStartAppInstance)
            }
            "kConsoleServiceStopAppInstance" => {
                Some(Self::KConsoleServiceStopAppInstance)
            }
            "kConsoleServiceStartAppInstanceResult" => {
                Some(Self::KConsoleServiceStartAppInstanceResult)
            }
            "kConsoleServiceStopAppInstanceResult" => {
                Some(Self::KConsoleServiceStopAppInstanceResult)
            }
            "kConsoleServiceCreateWallSession" => {
                Some(Self::KConsoleServiceCreateWallSession)
            }
            "kConsoleServiceCreateWallSessionResult" => {
                Some(Self::KConsoleServiceCreateWallSessionResult)
            }
            "kConsoleServiceRedeemConnectionTicket" => {
                Some(Self::KConsoleServiceRedeemConnectionTicket)
            }
            "kConsoleServiceRedeemConnectionTicketResult" => {
                Some(Self::KConsoleServiceRedeemConnectionTicketResult)
            }
            _ => None,
        }
    }
}
