// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrServiceHello {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub appkey: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrServiceHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub render_alive: bool,
    /// json format authorization info reported by the panel (may be empty)
    #[prost(string, tag = "4")]
    pub auth_info_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrServiceMessage {
    #[prost(enumeration = "SpvrServiceMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "10")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub hello: ::core::option::Option<SpvrServiceHello>,
    #[prost(message, optional, tag = "30")]
    pub heartbeat: ::core::option::Option<SpvrServiceHeartBeat>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SpvrServiceMessageType {
    KSpvrServiceHello = 0,
    KSpvrServiceHeartBeat = 1,
}
impl SpvrServiceMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KSpvrServiceHello => "kSpvrServiceHello",
            Self::KSpvrServiceHeartBeat => "kSpvrServiceHeartBeat",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kSpvrServiceHello" => Some(Self::KSpvrServiceHello),
            "kSpvrServiceHeartBeat" => Some(Self::KSpvrServiceHeartBeat),
            _ => None,
        }
    }
}
