// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrPanelHello {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrPanelHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub desktop_link: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub desktop_link_raw: ::prost::alloc::string::String,
    /// json format hardware system info
    #[prost(string, tag = "5")]
    pub sys_info_raw: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub device_ip_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub device_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrSysInfo {
    #[prost(string, tag = "1")]
    pub info: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrPanelMessage {
    #[prost(enumeration = "SpvrPanelMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "10")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub hello: ::core::option::Option<SpvrPanelHello>,
    #[prost(message, optional, tag = "30")]
    pub heartbeat: ::core::option::Option<SpvrPanelHeartBeat>,
    #[prost(message, optional, tag = "40")]
    pub sys_info: ::core::option::Option<SpvrSysInfo>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SpvrPanelMessageType {
    KSpvrPanelHello = 0,
    KSpvrPanelHeartBeat = 1,
}
impl SpvrPanelMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KSpvrPanelHello => "kSpvrPanelHello",
            Self::KSpvrPanelHeartBeat => "kSpvrPanelHeartBeat",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kSpvrPanelHello" => Some(Self::KSpvrPanelHello),
            "kSpvrPanelHeartBeat" => Some(Self::KSpvrPanelHeartBeat),
            _ => None,
        }
    }
}
