// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrClientHello {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrClientHeartBeat {
    #[prost(int64, tag = "1")]
    pub hb_index: i64,
    /// !!thunder sdk!! heartbeat duration \< 10'000 or not
    /// \< 10'000 -> alive
    ///
    /// >
    /// > 10'000 -> died
    #[prost(bool, tag = "2")]
    pub connection_alive: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpvrClientMessage {
    #[prost(enumeration = "SpvrClientMessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(string, tag = "10")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub hello: ::core::option::Option<SpvrClientHello>,
    #[prost(message, optional, tag = "30")]
    pub heartbeat: ::core::option::Option<SpvrClientHeartBeat>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SpvrClientMessageType {
    KSpvrClientHello = 0,
    KSpvrClientHeartBeat = 1,
}
impl SpvrClientMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KSpvrClientHello => "kSpvrClientHello",
            Self::KSpvrClientHeartBeat => "kSpvrClientHeartBeat",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kSpvrClientHello" => Some(Self::KSpvrClientHello),
            "kSpvrClientHeartBeat" => Some(Self::KSpvrClientHeartBeat),
            _ => None,
        }
    }
}
