[package]
name = "gr_guard"
version.workspace = true
edition.workspace = true

[[bin]]
name = "GammaRayGuard"
path = "src/main.rs"

[dependencies]
gr_base = { path = "../../rust_base/gr_base" }
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "time", "net"] }
tokio-tungstenite = { version = "0.27.0", features = ["rustls-tls-webpki-roots", "tokio-rustls"] }
tracing = "0.1.44"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }

