add_subdirectory(px_3rdparty)
#add_subdirectory(px_capture)
add_subdirectory(px_encoder)
add_subdirectory(px_message)
add_subdirectory(px_ft_engine)
add_subdirectory(px_media_record)
add_subdirectory(px_common)
add_subdirectory(px_opus_codec)
add_subdirectory(px_voice_call)
add_subdirectory(px_steam_manager)
add_subdirectory(px_controller)
add_subdirectory(px_client_sdk)
add_subdirectory(px_qt_widget)
add_subdirectory(px_relay_client)
add_subdirectory(px_server_protocol)
add_subdirectory(px_console_client)
add_subdirectory(px_webrtc_client)
add_subdirectory(px_account_sdk)
add_subdirectory(px_profile_client)
