#pragma once

#include <cstdint>
#include <string_view>

namespace px::ui {

enum class Language : std::uint8_t {
    English,
    SimplifiedChinese,
};

enum class TextId : std::uint8_t {
    RenderNodeConsole,
    RemoteControl,
    CloudApplications,
    ServerStatus,
    Security,
    Settings,
    Hardware,
    ExitPrograms,
    SettingsNetwork,
    ConnectionAddresses,
    Authorization,
    ResolvedControlEndpoints,
    Supervisor,
    NodeManagement,
    Relay,
    ReliableRoutedConnection,
    NodePublicAddress,
    OptionalPublicAddress,
    PublicAddressHint,
    NodeListeningPorts,
    ServiceManagementPort,
    ServiceManagementPurpose,
    DesktopConnectionPort,
    DesktopConnectionPurpose,
    ApplicationPortPool,
    ApplicationPortPurpose,
    RtcMediaPool,
    RtcPortPurpose,
    PanelListeningPort,
    PanelListeningPurpose,
    Save,
    Verify,
    InvalidAuthorization,
    InvalidPublicAddress,
    Verifying,
    Verified,
    Saving,
    Saved,
    OperationFailed,
    RestartRenderPrompt,
    RestartNow,
    Later,
    PreviewInitialStatus,
    PreviewSavedStatus,
    English,
    SimplifiedChinese,
    DarkTheme,
    LightTheme,
    ThisDevice,
    DeviceId,
    TemporaryPassword,
    DeviceName,
    ConnectionInformation,
    DesktopLink,
    WebClientAddress,
    Copy,
    Open,
    Show,
    Hide,
    RemoteDeviceId,
    Connect,
    ConnectedDevices,
    Online,
    Offline,
    StartControl,
    ViewOnly,
    StopControl,
    ManagerService,
    NoRemoteDevices,
    Refresh,
    Application,
    ApplicationState,
    Running,
    Stopped,
    StartApplication,
    EnterApplication,
    StopApplication,
    ForceTcp,
    ForceRelay,
    NoCloudApplications,
    ControllerDriver,
    RenderService,
    NodeService,
    Ready,
    Unavailable,
    Install,
    Restart,
    NetworkAddresses,
    Wired,
    Wireless,
    AudioFormat,
    General,
    Network,
    Controller,
    About,
    EncoderSettings,
    BitrateMbps,
    FrameRate,
    VideoCodec,
    ResizeResolution,
    Width,
    Height,
    CaptureAudio,
    InvalidBitrate,
    InvalidFrameRate,
    InvalidResolution,
    UnsupportedResolution,
    InvalidAspectRatio,
    ClientWindowSettings,
    MaximizeClient,
    DisplayClientLogo,
    ColorfulTitleBar,
    MaximumScreens,
    PreferredDecoder,
    Automatic,
    HardwareDecoder,
    SoftwareDecoder,
    RecordingPath,
    SecuritySettings,
    DisconnectAutoLock,
    LongTermPassword,
    ConfirmPassword,
    SetPassword,
    PasswordInvalid,
    MaintenanceTools,
    ClearData,
    ClearDataPrompt,
    Clear,
    Cancel,
    Version,
    AboutDescription,
    CheckForUpdates,
    Website,
    VisitHistory,
    FileTransferHistory,
    ClearAll,
    NoSecurityRecords,
    ConnectionType,
    Result,
    StartTime,
    EndTime,
    VisitorDevice,
    TargetDevice,
    Duration,
    Direction,
    FileName,
    Actions,
    CopyJson,
    Delete,
    EnterLongTermPassword,
    UpdatingPassword,
    PasswordUpdated,
    PasswordRemoteFailed,
    LogDestination,
    CollectLogs,
    Collecting,
    LogCollectionCompleted,
    LogCollectionFailed,
    Account,
    Guest,
    Login,
    Logout,
    Register,
    Username,
    Password,
    Confirm,
    Working,
    AccountOperationFailed,
    AccountInputInvalid,
    More,
    FileTransfer,
    LockDevice,
    RestartDevice,
    ShutdownDevice,
    ConfirmDeviceAction,
    EditDevice,
    Host,
    Port,
    DeviceSettings,
    EnableClipboard,
    SplitWindows,
    ForceSoftware,
    WaitForDebugger,
    ForceGdiCapture,
    DisableVulkan,
    InvalidDeviceSettings,
    ConnectedClients,
    MigrationPending,
    VoiceCallIncoming,
    VoiceCallRequest,
    VoiceCallWarning,
    VoiceCallCountdown,
    VoiceCallAccept,
    VoiceCallReject,
    DeviceList,
    SearchDevices,
    AllDevices,
    DeviceDetails,
    NoDeviceSelected,
    RemoveDevicePrompt,
    Count,
};

class Localizer final {
  public:
    explicit Localizer(Language language = Language::SimplifiedChinese) noexcept;

    void SetLanguage(Language language) noexcept;
    Language CurrentLanguage() const noexcept;
    std::string_view Text(TextId id) const noexcept;

  private:
    Language language_{Language::SimplifiedChinese};
};

bool CatalogsAreComplete() noexcept;

} // namespace px::ui
