[package]
name = "px_server_service"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[dependencies]
tokio = { version = "1.43", features = ["rt-multi-thread"] }
tokio-util = "0.7"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_Services"] }
