#pragma once

#include <cstdint>
#include <string_view>

namespace px::client::imgui {

enum class ClientText : std::uint8_t {
    Controls,
    Resolution,
    VirtualDisplays,
    AddVirtualDisplay,
    RemoveVirtualDisplay,
    Files,
    SecureAttention,
    Audio,
    StopRecording,
    Record,
    Screenshot,
    ScreenshotFailed,
    HangUp,
    Voice,
    MuteMicrophone,
    MuteSpeaker,
    Statistics,
    Hide,
    FileTransfer,
    RemotePath,
    Open,
    LocalPath,
    UploadLocalPath,
    DownloadSelection,
    RemoteFiles,
    Name,
    Type,
    Size,
    Folder,
    File,
    Transfers,
    Download,
    Upload,
    Cancel,
    DestinationExists,
    ApplyToAll,
    Overwrite,
    Skip,
    ConnectionRejected,
    AuthorizationRejected,
    DeviceOccupied,
    SessionPolicyRejected,
    SessionTakenOver,
    TransportRejected,
    ConnectionFailed,
    Ok,
    Light,
    Dark,
    Fullscreen,
    WaitingForFrame,
    Connecting,
    Connected,
    MediaUnavailable,
    Rejected,
    Disconnected,
    MediaUnavailableDetail,
    DisconnectedDetail,
    Display,
    Control,
    Tools,
    Settings,
    EnhancedVisualEffects,
    Monitor,
    FrameRate,
    ControlDescription,
    LocalComputer,
    RemoteComputer,
    Back,
    Up,
    Search,
    Refresh,
    Send,
    Receive,
    Resume,
    Modified,
    TransferQueue,
    NoTransfers,
    FileTransferConnected,
    NewFolder,
    Rename,
    Delete,
    Create,
    ItemName,
    ConfirmDelete,
    OperationSucceeded,
    OperationFailed,
    More,
    ShowHiddenFiles,
    SelectAll,
    UnselectAll,
    Home,
    ClearCompleted,
    Completed,
    Failed,
    CloseTransfersTitle,
    CloseTransfersDetail,
    Close,
    RemoteOperationQueueFailed,
    DroppedUploadStarted,
    FilesSelected,
    Count,
};

[[nodiscard]] std::string_view ClientTextValue(ClientText id, bool english) noexcept;

} // namespace px::client::imgui
