#include "client_text.h"

#include <array>
#include <utility>

namespace px::client::imgui {
namespace {
constexpr auto kCount = std::to_underlying(ClientText::Count);
using Catalog = std::array<std::string_view, kCount>;

constexpr Catalog kEnglish{"Controls",
                           "Resolution",
                           "Virtual displays",
                           "Files",
                           "Secure attention",
                           "Audio",
                           "Stop recording",
                           "Record",
                           "Screenshot",
                           "Screenshot failed",
                           "Hang up",
                           "Voice",
                           "Mute mic",
                           "Mute speaker",
                           "Statistics",
                           "Hide",
                           "File transfer",
                           "Remote path",
                           "Open",
                           "Local path",
                           "Upload local path",
                           "Download selection",
                           "Remote files",
                           "Name",
                           "Type",
                           "Size",
                           "Folder",
                           "File",
                           "Transfers",
                           "Download",
                           "Upload",
                           "Cancel",
                           "The destination already exists:",
                           "Apply to all",
                           "Overwrite",
                           "Skip",
                           "The remote connection was rejected.",
                           "The device password was rejected.",
                           "The device is in use. Please try again in a few seconds.",
                           "The device policy does not allow this connection.",
                           "This session was taken over by another controller.",
                           "The remote control channel rejected the connection.",
                           "Pixels connection failed",
                           "OK",
                           "Light",
                           "Dark",
                           "Fullscreen",
                           "Waiting for the first video frame...",
                           "Connecting...",
                           "Connected",
                           "Media unavailable",
                           "Connection rejected",
                           "Disconnected; retrying...",
                           "Video and audio are temporarily unavailable. Control and file transfer remain connected; Pixels is retrying media.",
                           "The connection was interrupted. Pixels is retrying; check the network if it does not recover."};

constexpr Catalog kChinese{"控制栏",
                           "分辨率",
                           "虚拟屏",
                           "文件",
                           "安全注意键",
                           "声音",
                           "停止录制",
                           "录制",
                           "截图",
                           "截图失败",
                           "挂断",
                           "语音",
                           "麦克风静音",
                           "扬声器静音",
                           "统计",
                           "隐藏",
                           "文件传输",
                           "远端路径",
                           "打开",
                           "本地路径",
                           "上传本地路径",
                           "下载选中项",
                           "远端文件",
                           "名称",
                           "类型",
                           "大小",
                           "目录",
                           "文件",
                           "传输任务",
                           "下载",
                           "上传",
                           "取消",
                           "目标文件已存在：",
                           "应用到全部",
                           "覆盖",
                           "跳过",
                           "远程连接被拒绝。",
                           "设备密码校验未通过。",
                           "设备正在使用或处于 5 秒重连宽限期，请稍后再试。",
                           "设备策略不允许本次连接。",
                           "当前会话已被其他控制端接管。",
                           "远程控制通道拒绝了连接。",
                           "Pixels 连接失败",
                           "确定",
                           "浅色",
                           "深色",
                           "全屏",
                           "正在等待首帧画面…",
                           "正在连接…",
                           "已连接",
                           "媒体不可用",
                           "连接被拒绝",
                           "连接已断开，正在重试…",
                           "音视频暂时不可用，控制与文件传输仍保持连接；Pixels 正在重试媒体通道。",
                           "连接已中断，Pixels 正在重试；如果长时间未恢复，请检查网络。"};
static_assert(kEnglish.size() == kChinese.size());
} // namespace

std::string_view ClientTextValue(const ClientText id, const bool english) noexcept {
    const auto index = std::to_underlying(id);
    return index < kCount ? (english ? kEnglish[index] : kChinese[index]) : std::string_view{};
}

} // namespace px::client::imgui
