product = "android"
company = "Pixels"
product_version = "1.0.6"
product_version_code = 10006
capabilities = [
    "desktop_client",
    "file_transfer",
    "rdp_client",
    "cloud_app_catalog",
    "system_information",
]
