product = "client"
edition = "CLIENT"
company = "Pixels"
product_version = "3.3.71"
product_version_code = 30371
package_groups = ["desktop_client"]

capabilities = [
    "desktop_client",
    "file_transfer",
    "rdp_client",
    "cloud_app_catalog",
    "system_information",
]
