use crate::{check_postgresql_administrator, SetupDatabaseError};
use px_pg::{DatabaseConfig, Transport};
use rand::RngCore;
use sqlx::Acquire;
use std::time::Duration;
use url::Url;
use uuid::Uuid;
use zeroize::Zeroizing;

/// Credentials are generated by the setup owner and never written to a log or command line.
pub struct ConsoleDatabaseCredentials {
    pub owner_password: Zeroizing<String>,
    pub runtime_password: Zeroizing<String>,
}

impl ConsoleDatabaseCredentials {
    pub fn generate() -> Self {
        let mut owner_secret = Zeroizing::new([0_u8; 32]);
        let mut runtime_secret = Zeroizing::new([0_u8; 32]);
        rand::rng().fill_bytes(owner_secret.as_mut());
        rand::rng().fill_bytes(runtime_secret.as_mut());
        Self {
            owner_password: Zeroizing::new(hex::encode(owner_secret.as_ref())),
            runtime_password: Zeroizing::new(hex::encode(runtime_secret.as_ref())),
        }
    }

    pub fn new(
        owner_password: Zeroizing<String>,
        runtime_password: Zeroizing<String>,
    ) -> Result<Self, SetupDatabaseError> {
        if !valid_password(&owner_password)
            || !valid_password(&runtime_password)
            || owner_password == runtime_password
        {
            return Err(SetupDatabaseError::Configuration);
        }
        Ok(Self {
            owner_password,
            runtime_password,
        })
    }
}

/// Provision only an empty Console database. Existing database or role names are never adopted.
/// On an interrupted first run, the administrator must inspect partial resources before retrying.
pub async fn provision_fresh_console_database(
    administrator_url: Zeroizing<String>,
    deployment_id: Uuid,
    credentials: &ConsoleDatabaseCredentials,
) -> Result<(Zeroizing<String>, Zeroizing<String>), SetupDatabaseError> {
    if deployment_id.is_nil() {
        return Err(SetupDatabaseError::Configuration);
    }
    check_postgresql_administrator(administrator_url.clone()).await?;
    let administrator_configuration =
        DatabaseConfig::parse(&administrator_url, Transport::VerifyFull)
            .and_then(|configuration| configuration.with_pool_limits(1, Duration::from_secs(5)))
            .map_err(|_| SetupDatabaseError::Configuration)?;
    let administrator_pool = administrator_configuration
        .connect()
        .await
        .map_err(|_| SetupDatabaseError::Unavailable)?;
    let provision_result = async {
        let mut connection = administrator_pool
            .acquire()
            .await
            .map_err(|_| SetupDatabaseError::Unavailable)?;
        let lock_acquired: bool =
            sqlx::query_scalar("SELECT pg_catalog.pg_try_advisory_lock(22092601)")
                .fetch_one(&mut *connection)
                .await
                .map_err(|_| SetupDatabaseError::Operation)?;
        if !lock_acquired {
            return Err(SetupDatabaseError::Operation);
        }
        let existing: (bool, bool) = sqlx::query_as(
            "SELECT EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE rolname IN \
             ('pixels_console_owner','pixels_console_runtime')), \
             EXISTS(SELECT 1 FROM pg_catalog.pg_database WHERE datname='pixels_console')",
        )
        .fetch_one(&mut *connection)
        .await
        .map_err(|_| SetupDatabaseError::Operation)?;
        if existing.0 || existing.1 {
            return Err(SetupDatabaseError::AlreadyExists);
        }

        let mut role_transaction = connection
            .begin()
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;
        sqlx::query("SELECT pg_catalog.set_config('pixels.setup_owner_password',$1,true)")
            .bind(credentials.owner_password.as_str())
            .execute(&mut *role_transaction)
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;
        sqlx::query("SELECT pg_catalog.set_config('pixels.setup_runtime_password',$1,true)")
            .bind(credentials.runtime_password.as_str())
            .execute(&mut *role_transaction)
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;
        sqlx::query(
            "DO $pixels$ BEGIN \
             EXECUTE format('CREATE ROLE pixels_console_owner LOGIN NOINHERIT NOSUPERUSER \
             NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD %L', \
             pg_catalog.current_setting('pixels.setup_owner_password')); \
             EXECUTE format('CREATE ROLE pixels_console_runtime LOGIN NOINHERIT NOSUPERUSER \
             NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD %L', \
             pg_catalog.current_setting('pixels.setup_runtime_password')); END $pixels$",
        )
        .execute(&mut *role_transaction)
        .await
        .map_err(|_| SetupDatabaseError::Operation)?;
        role_transaction
            .commit()
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;

        sqlx::query("CREATE DATABASE pixels_console OWNER pixels_console_owner")
            .execute(&mut *connection)
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;
        sqlx::query("REVOKE ALL ON DATABASE pixels_console FROM PUBLIC")
            .execute(&mut *connection)
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;
        sqlx::query("GRANT CONNECT ON DATABASE pixels_console TO pixels_console_runtime")
            .execute(&mut *connection)
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;
        Ok(())
    }
    .await;
    administrator_pool.close().await;
    provision_result?;

    let owner_url = role_url(
        &administrator_url,
        "pixels_console_owner",
        &credentials.owner_password,
    )?;
    let runtime_url = role_url(
        &administrator_url,
        "pixels_console_runtime",
        &credentials.runtime_password,
    )?;
    let owner_configuration = DatabaseConfig::parse(&owner_url, Transport::VerifyFull)
        .map_err(|_| SetupDatabaseError::Configuration)?;
    let owner_pool = owner_configuration
        .connect()
        .await
        .map_err(|_| SetupDatabaseError::Unavailable)?;
    let initialize_result = async {
        let mut transaction = owner_pool
            .begin()
            .await
            .map_err(|_| SetupDatabaseError::Operation)?;
        for statement in [
            "REVOKE ALL ON SCHEMA public FROM PUBLIC",
            "CREATE SCHEMA pixels",
            "CREATE TABLE pixels.deployment_identity (singleton boolean PRIMARY KEY DEFAULT true \
             CHECK(singleton), deployment_id uuid NOT NULL, service text NOT NULL \
             CHECK(service IN ('console','auth','desk')))",
        ] {
            sqlx::query(statement)
                .execute(&mut *transaction)
                .await
                .map_err(|_| SetupDatabaseError::Operation)?;
        }
        sqlx::query(
            "INSERT INTO pixels.deployment_identity(deployment_id,service) VALUES ($1,'console')",
        )
        .bind(deployment_id)
        .execute(&mut *transaction)
        .await
        .map_err(|_| SetupDatabaseError::Operation)?;
        for statement in [
            "GRANT USAGE ON SCHEMA pixels TO pixels_console_runtime",
            "GRANT SELECT ON pixels.deployment_identity TO pixels_console_runtime",
        ] {
            sqlx::query(statement)
                .execute(&mut *transaction)
                .await
                .map_err(|_| SetupDatabaseError::Operation)?;
        }
        transaction
            .commit()
            .await
            .map_err(|_| SetupDatabaseError::Operation)
    }
    .await;
    owner_pool.close().await;
    initialize_result?;
    Ok((owner_url, runtime_url))
}

fn role_url(
    administrator_url: &str,
    role: &str,
    password: &str,
) -> Result<Zeroizing<String>, SetupDatabaseError> {
    let mut parsed_url =
        Url::parse(administrator_url).map_err(|_| SetupDatabaseError::Configuration)?;
    parsed_url
        .set_username(role)
        .map_err(|_| SetupDatabaseError::Configuration)?;
    parsed_url
        .set_password(Some(password))
        .map_err(|_| SetupDatabaseError::Configuration)?;
    parsed_url.set_path("/pixels_console");
    Ok(Zeroizing::new(parsed_url.to_string()))
}

fn valid_password(password: &str) -> bool {
    (32..=128).contains(&password.len())
        && password
            .bytes()
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, b'-' | b'_'))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn setup_passwords_are_distinct_bounded_and_pgpass_safe() {
        assert!(ConsoleDatabaseCredentials::new(
            Zeroizing::new("a".repeat(32)),
            Zeroizing::new("b".repeat(32)),
        )
        .is_ok());
        for invalid_password in ["a".repeat(31), format!("{}:", "a".repeat(31))] {
            assert!(ConsoleDatabaseCredentials::new(
                Zeroizing::new(invalid_password),
                Zeroizing::new("b".repeat(32)),
            )
            .is_err());
        }
        assert!(ConsoleDatabaseCredentials::new(
            Zeroizing::new("a".repeat(32)),
            Zeroizing::new("a".repeat(32)),
        )
        .is_err());
        let generated_credentials = ConsoleDatabaseCredentials::generate();
        assert!(valid_password(&generated_credentials.owner_password));
        assert!(valid_password(&generated_credentials.runtime_password));
        assert_ne!(
            generated_credentials.owner_password,
            generated_credentials.runtime_password
        );
    }

    #[test]
    fn role_urls_keep_the_tls_root_and_target_only_console() {
        let role_database_url = role_url(
            "postgresql://postgres:secret@pg.customer.example/postgres?sslrootcert=/etc/pixels/pg-ca.crt",
            "pixels_console_owner",
            &"a".repeat(32),
        )
        .unwrap();
        let parsed_url = Url::parse(&role_database_url).unwrap();
        assert_eq!(parsed_url.username(), "pixels_console_owner");
        assert_eq!(parsed_url.path(), "/pixels_console");
        assert_eq!(
            parsed_url.query(),
            Some("sslrootcert=/etc/pixels/pg-ca.crt")
        );
    }
}
