export class CmsEvent {
  constructor(
    public event_id: string = '',
    public total: number = 0,
    public timestamp: number = 0,
    public readable_timestamp: string = '',
    public first_timestamp: number = 0,
    public first_readable_timestamp: string = '',
    public occurrence_count: number = 0,
    public event_type: string = '',
    public device_id: string = '',
    public device_ip: string = '',
    public device_name: string = '',
    public message: string = '',
    //public current_sys_info: SysInfo | null = null,
    public user_id: string = '',
    public user_name: string = '',
    public user_update_values: Record<string, string> = {},
    public log_path: string = '',
    public cpu_usage: number = 0,
    public mem_usage: number = 0,
    public disk_usage: number = 0,
    public disk_path: string = '',
    public gpu_usage: number = 0,
    public gpu_id: string = '',
    public gpu_name: string = '',
    public actor_type: string = '',
    public actor_id: string = '',
    public action: string = '',
    public result: string = '',
    public target_type: string = '',
    public target_id: string = '',
    public reason: string = '',
    public metadata: Record<string, string> = {},
  ) {}
}
