[package]
name = "gr_user_proxy"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "GammaRayUserProxy"
path = "src/main.rs"

[dependencies]
gr_base = { path = "../../rust_base/gr_base" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures-util = "0.3.31"
prost = "0.13"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "time", "net", "sync"] }
tokio-tungstenite = { version = "0.27.0", features = ["rustls-tls-webpki-roots", "tokio-rustls"] }
tracing = "0.1.44"
windows-implement = "0.60.2"
windows-core = "0.62.2"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"
