[workspace]
members = [
    "px_sysinfo",
    "px_user_proxy",
    "px_service",
    "px_service/service_core",
    "px_service/service_manager",
    "px_uninstall",
]

resolver = "2"

[workspace.package]
version = "3.3.36"
edition = "2021"

[patch.crates-io]
proc-macro-error2 = { git = "https://github.com/GnomedDev/proc-macro-error-2.git", rev = "53ff94b61c678593158db1a3d50269c6f0de0db7" }
