[workspace]
members = [
    "gr_sysinfo",
    "gr_user_proxy",
    "gr_service",
    "gr_service/service_core",
    "gr_service/service_manager",
    "gr_crash_reporter",
    "gr_uninstall",
]

resolver = "2"

[workspace.package]
version = "3.2.58"
edition = "2021"

[patch.crates-io]
proc-macro-error2 = { git = "https://github.com/GnomedDev/proc-macro-error-2.git", rev = "53ff94b61c678593158db1a3d50269c6f0de0db7" }
