# Relocatable, pinned SDK. Build/install it with build_cpp_rdp_sdk.bat;
# never use Qt 5 demo binaries or an implicitly selected system FreeRDP.
set(GAMMARAY_RDP_SDK_ROOT "${CMAKE_SOURCE_DIR}/.cache/rdp_sdk" CACHE PATH "Pinned GammaRay FreeRDP 3.31 SDK")
file(READ "${GAMMARAY_RDP_SDK_ROOT}/include/freerdp3/freerdp/version.h" _rdp_version)
if(NOT _rdp_version MATCHES "FREERDP_GIT_REVISION \"aa8650b\"")
    message(FATAL_ERROR "RDP SDK must use pinned FreeRDP aa8650b300aa4cabd85d9c72b431301509b9043f")
endif()
file(READ "${GAMMARAY_RDP_SDK_ROOT}/gammaray-rdp-sdk.json" _rdp_manifest)
string(JSON _rdp_revision GET "${_rdp_manifest}" freerdp_revision)
string(JSON _rdp_patch GET "${_rdp_manifest}" freerdp_patch_sha256)
file(SHA256 "${CMAKE_SOURCE_DIR}/patches/freerdp/0001-mf-output-state.patch" _rdp_expected_patch)
string(TOLOWER "${_rdp_patch}" _rdp_patch)
if(NOT _rdp_patch STREQUAL _rdp_expected_patch)
    message(FATAL_ERROR "RDP SDK does not contain the reviewed decoder patch")
endif()
string(JSON _rdp_decoder GET "${_rdp_manifest}" h264_decoder)
if(NOT _rdp_decoder STREQUAL "media-foundation")
    message(FATAL_ERROR "RDP SDK decoder profile does not match this Windows Client build")
endif()
if(NOT _rdp_revision STREQUAL "aa8650b300aa4cabd85d9c72b431301509b9043f")
    message(FATAL_ERROR "RDP SDK full revision does not match the pinned source")
endif()
foreach(_rdp_name winpr3 freerdp3 freerdp-client3)
    foreach(_rdp_file "lib/${_rdp_name}.lib" "bin/${_rdp_name}.dll")
        if(NOT EXISTS "${GAMMARAY_RDP_SDK_ROOT}/${_rdp_file}")
            message(FATAL_ERROR "Missing pinned RDP SDK artifact: ${_rdp_file}")
        endif()
    endforeach()
    file(SHA256 "${GAMMARAY_RDP_SDK_ROOT}/bin/${_rdp_name}.dll" _rdp_actual_hash)
    string(JSON _rdp_expected_hash GET "${_rdp_manifest}" runtime_sha256 "${_rdp_name}.dll")
    string(TOLOWER "${_rdp_expected_hash}" _rdp_expected_hash)
    if(NOT _rdp_actual_hash STREQUAL _rdp_expected_hash)
        message(FATAL_ERROR "RDP SDK runtime hash mismatch: ${_rdp_name}")
    endif()
    add_library(gammaray_${_rdp_name} SHARED IMPORTED GLOBAL)
    set_target_properties(gammaray_${_rdp_name} PROPERTIES
        IMPORTED_IMPLIB "${GAMMARAY_RDP_SDK_ROOT}/lib/${_rdp_name}.lib"
        IMPORTED_LOCATION "${GAMMARAY_RDP_SDK_ROOT}/bin/${_rdp_name}.dll")
endforeach()
add_library(gammaray_rdp_sdk INTERFACE)
target_include_directories(gammaray_rdp_sdk SYSTEM INTERFACE
    "${GAMMARAY_RDP_SDK_ROOT}/include/freerdp3" "${GAMMARAY_RDP_SDK_ROOT}/include/winpr3")
target_link_libraries(gammaray_rdp_sdk INTERFACE gammaray_freerdp-client3 gammaray_freerdp3 gammaray_winpr3)

function(gammaray_stage_rdp_client target)
    file(READ "${GAMMARAY_RDP_SDK_ROOT}/gammaray-rdp-sdk.json" _rdp_manifest)
    add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:${target}>/rdp/licenses")
    foreach(_license FreeRDP-LICENSE openssl-LICENSE libusb-LICENSE zlib-LICENSE cjson-LICENSE openh264-LICENSE)
        if(NOT EXISTS "${GAMMARAY_RDP_SDK_ROOT}/licenses/${_license}")
            message(FATAL_ERROR "Missing RDP runtime license: ${_license}")
        endif()
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${GAMMARAY_RDP_SDK_ROOT}/licenses/${_license}" "$<TARGET_FILE_DIR:${target}>/rdp/licenses/${_license}")
    endforeach()
    add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${GAMMARAY_RDP_SDK_ROOT}/gammaray-rdp-sdk.json" "$<TARGET_FILE_DIR:${target}>/rdp/sdk.json")
    foreach(_name freerdp-client3.dll freerdp3.dll winpr3.dll libusb-1.0.dll libssl-3-x64.dll libcrypto-3-x64.dll zlib1.dll cjson.dll legacy.dll openh264-6.dll)
        if(NOT EXISTS "${GAMMARAY_RDP_SDK_ROOT}/bin/${_name}")
            message(FATAL_ERROR "Incomplete RDP SDK runtime: ${_name}")
        endif()
        file(SHA256 "${GAMMARAY_RDP_SDK_ROOT}/bin/${_name}" _runtime_hash)
        string(JSON _expected_hash GET "${_rdp_manifest}" runtime_sha256 "${_name}")
        string(TOLOWER "${_expected_hash}" _expected_hash)
        if(NOT _runtime_hash STREQUAL _expected_hash)
            message(FATAL_ERROR "RDP runtime dependency hash mismatch: ${_name}")
        endif()
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${GAMMARAY_RDP_SDK_ROOT}/bin/${_name}" "$<TARGET_FILE_DIR:${target}>/${_name}")
    endforeach()
endfunction()
