syntax = "proto3";

package console_relay;

// Between servers
// Console <---> Relay
//

enum ConsoleRelayMessageType {
  kHello = 0;
  kHeartBeat = 1;
}

message ConsoleRelayHello {
  string srv_name = 1;
  string srv_w3c_ip = 3;
  string srv_local_ip = 4;
  uint32 srv_grpc_port = 5;
  uint32 srv_working_port = 6;
  string appkey = 7;
}

message ConsoleRelayHeartBeat {
  int64 hb_index = 1;
}

message ConsoleRelayMessage {
  ConsoleRelayMessageType msg_type = 1;
  string server_id = 3;
  ConsoleRelayHello hello = 5;
  ConsoleRelayHeartBeat heartbeat = 10;
}