[package]
name = "gr_uninstall"
version.workspace = true
edition.workspace = true

[[bin]]
name = "GammaRayUninstall"
path = "src/main.rs"

[dependencies]
gr_base = { path = "../../rust_base/gr_base" }
clap = { version = "4.5", features = ["derive"] }
sysinfo = "0.37.0"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Services",
    "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
] }
