#pragma once

#include <string>

namespace px {

// Adds public equivalents for private UDP host candidates without changing the
// candidates generated by libwebrtc. An empty or invalid configured address is
// deliberately a no-op so a node never publishes a visitor's source address.
[[nodiscard]] std::string AddAdvertisedIpv4HostCandidates(const std::string& advertised_ipv4, const std::string& answer_sdp);

} // namespace px
