include(${GR_PROJECT_PATH}/version.cmake)
include_directories(${GR_PROJECT_BINARY_PATH})
add_subdirectory(gr_base)
add_subdirectory(gr_client)
add_subdirectory(GammaRay)
add_subdirectory(gr_panel)
add_subdirectory(gr_render)
#add_subdirectory(GammaRayServer)
#add_subdirectory(render_plugins)
add_subdirectory(panel_companion)
add_subdirectory(skins)
