include(${CMAKE_CURRENT_SOURCE_DIR}/gr_base/version.cmake)
include_directories(${CMAKE_BINARY_DIR}/src/gr_base)
add_subdirectory(gr_deps)
add_subdirectory(gr_base)
add_subdirectory(gr_client)
add_subdirectory(gr_panel)
add_subdirectory(gr_render)
#add_subdirectory(GammaRayServer)
#add_subdirectory(render_plugins)
