set(GR_RENDER_PATH ${CMAKE_SOURCE_DIR}/src/gr_render CACHE PATH "Path to gr_render sources")
set(GR_PROJECT_PATH ${CMAKE_SOURCE_DIR}/src/GammaRay)
if (BUILD_PREMIUM)
    set(GR_PROJECT_BINARY_PATH ${CMAKE_BINARY_DIR}/src/GammaRay)
else()
    set(GR_PROJECT_BINARY_PATH ${CMAKE_BINARY_DIR})
endif()

include(${GR_PROJECT_PATH}/version.cmake)

add_subdirectory(gr_base)
add_subdirectory(gr_client)
add_subdirectory(GammaRay)
add_subdirectory(gr_panel)
add_subdirectory(gr_render)
#add_subdirectory(GammaRayServer)
#add_subdirectory(render_plugins)
add_subdirectory(panel_companion)
add_subdirectory(skins)
