if(PLUGIN_NET_UDP_ENABLED)
    add_subdirectory(net_udp)
else()
    message(STATUS "net_udp is disabled (PLUGIN_NET_UDP_ENABLED=OFF)")
endif()
add_subdirectory(net_rtc)
add_subdirectory(net_ws)
add_subdirectory(net_relay)
add_subdirectory(ffmpeg_encoder)
add_subdirectory(amf_encoder)
add_subdirectory(nvenc_encoder)
add_subdirectory(dda_capture)
add_subdirectory(gdi_capture)
#add_subdirectory(px_vr_plugin)
add_subdirectory(net_rtc_local)
