add_subdirectory(px_3rdparty)
#add_subdirectory(px_capture_new)
add_subdirectory(px_encoder_new)
add_subdirectory(px_message_new)
add_subdirectory(px_common_new)
add_subdirectory(px_opus_codec_new)
add_subdirectory(px_steam_manager_new)
add_subdirectory(px_controller)
add_subdirectory(px_client_sdk_new)
add_subdirectory(px_qt_widget)
add_subdirectory(px_relay_client)
add_subdirectory(px_server_protocol)
add_subdirectory(px_cms_client)
add_subdirectory(px_webrtc_client)
add_subdirectory(px_account_sdk)
add_subdirectory(px_profile_client)
